version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: meu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: meu_banco
    ports:
      - "3306:3306"

